### ISSUE TITLE
Query integration should validate that a list_id and values are set

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-suppressionlist#15]
Currently if no list ID is set the integration throws an error on [line 4](https://github.com/activeprospect/leadconduit-integration-suppressionlist/blob/ee269be54b8cef35648b78a9a65815ca58b87353/src/query_item.coffee#L4) because `split()` cannot be called on `undefined`.

Implement the `validate()` function to skip this integration if the `list_id` or `values` are missing.

**Comment by cgrayson** [comment]
Duplicate of #11

**Comment by cgrayson** [comment]
Fixed in 0.6.0.
