### ISSUE TITLE
list_ids should be lowercased

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-suppressionlist#21]
SuppressionList ids ("URL names") are always lowercase.

**Comment by chasingSublimity** [comment]
This looks like it was fixed in #41. 

All url names are lowercased here:  https://github.com/activeprospect/leadconduit-integration-suppressionlist/blob/4e122801203beb2cb280efb78cb1683ce8f0664e/lib/helper.js#L7


Closing.
