### ISSUE TITLE
Query Item integration should skip when value to query is blank

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-suppressionlist#25]
Howdy,

I came upon this event. It appears that this was an isolated incident. 

https://next.leadconduit.com/events/55560d01912e50770334e6d7?event_id=55560d01912e50770334e6d8

SL returned a 404 error. However, leads from the same vendor, before and afterwards reported as successful delivery.

![screen shot 2015-05-18 at 9 43 11 am](https://cloud.githubusercontent.com/assets/8238417/7683174/e915c362-fd42-11e4-9d2b-045186e88fca.png)

**Comment by alexkwolfe** [comment]
Looks like this happened because the query is set up to use `phone_1` or `phone_2` but this lead did not have either of those values. The correct behavior would be to make the outcome a `skip` in this case.

**Comment by cgrayson** [comment]
Fixed in 1.0.1.
