### ISSUE TITLE
Please change the label for List ID to URL Name

### ISSUE THREAD

**Issue by activeprospect-support** [activeprospect/leadconduit-integration-suppressionlist#26]
Currently SL requests List ID in the integration.  
This is confusing, as what is needed to query / add / delete from a list is the URL name. 
List ID does not work.

![screen shot 2015-05-29 at 11 58 26 am](https://cloud.githubusercontent.com/assets/8238417/7887895/0b102308-05fa-11e5-82fa-16b83e2ac68a.png)

**Comment by zalary** [comment]
I'm not sure what is going on here, but the list_id *SHOULD* be what is needed here, not the url

The integration calls https://app.suppressionlist.com/exists/#{list_ids}

**Comment by alexkwolfe** [comment]
I think the issue is that SuppressionList expects the list name (aka the "URL Name")?

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/569/7888579/328a9508-05ff-11e5-8c8f-422e2dde1d23.png)

**Comment by alexkwolfe** [comment]
This is resolved.
