### ISSUE TITLE
Make sure that emails are correctly URL encoded

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-suppressionlist#28]
In order to do so, here is what needs to happen: 

1. Send test leads to a flow using SuppressionList in LC which contains emails with odd characters. For example: #1&2%3.

2. Once it's determined how the odd characters are handled, update the integration accordingly.

However, upon setting up a flow in staging which contains SuppressionList steps, it appears that SL is not working correctly. After sending a test email to the list, this error came up: SuppressionList error (412) Successfully authenticated, but account has none of the specified lists. 

Here is the lead: 
https://next.staging.leadconduit.com/events/556f2fea202cb7cf29a39863?event_id=556f2fea202cb7cf29a39864

Here is the list: 
https://staging.suppressionlist.com/#lists/556f2f9e4efbbe9742000006/edit

**Comment by alexkwolfe** [comment]
Staging LCN uses production SL.

**Comment by ros3bud** [comment]
Noted. @kcaponeAP ^^

**Comment by ros3bud** [comment]
In just trying to use a crazy email address for example purposes, it turns out that 
z!#$%^&*()_123@gmail.com shows up in LC as z! when not encoded.

When encoded and sent again it shows up correctly, but also fails SL because it's already in the list.

**Comment by alexkwolfe** [comment]
Per our conversation today, this particular email is a problem because it has an unencoded `&` character. Once it is URL encoded, the email is displayed correctly.

Related: https://github.com/activeprospect/leadconduit-client/issues/782
