### ISSUE TITLE
Validate emails before passing them along

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-suppressionlist#30]
Related to Issue #28 we should use validation to not send invalid emails.

Since this integration allows for a pseudo-array of values, possibly split them, check the validity of each, removing invalid entries, then check that values isn't blank

This opens the wormhole of letting the user that one or more email addresses wasn't attempted/successfully sent to SL.  But in reality that problem is going to exist whether we do this validation or not, so I'd argue for validating (since most people are using one email at a time)

**Comment by alexkwolfe** [comment]
Isn't the problem that we don't know if they're storing emails or some other kind of value? Say phone?

I guess we could just make sure that if a `valid` property is on the value that it's `true`.

**Comment by alexkwolfe** [comment]
Also, what's the disadvantage of storing invalid values?

**Comment by zalary** [comment]
I always forget SL can be used for storing whatever and not just emails, so maybe this is a poor argument.  

I do think it's potentially problematic to pass things like z! to a list (z!&123 and z!&789 would be equally misconstrued by LC and you wouldn't be suppressioning either of the things you thought you were).  In this particular example it's an MD5 list, not an email type list, and I guess that matches the 'email address' collected by LC, so maybe it's ok.  

This is possibly a larger issue of how LC handles un-encoded characters and how or if to warn submitters that their data was potentially mishandled.

**Comment by alexkwolfe** [comment]
The unencoded characters thing isn't a LC issue, it's an HTTP issue. If you have an ampersand in a query string value it has to be encoded.

**Comment by zalary** [comment]
What I am trying to get at, I guess, is letting users know that the submitted address wasn't captured or potentially isn't worth sending to SL.  [Client Issue #782](https://github.com/activeprospect/leadconduit-client/issues/782) partially addresses it.  Acceptance criteria will probably address the rest of it.
