### ISSUE TITLE
Duplicated list IDs in SuppressionList

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-suppressionlist#31]
Question:

The SL step in LCN relies on the URL name to query / add / delete a value from a list.

All of the URL names are the same: dual_list ...

My question is, SL allows you to create multiple versions of the same, how will suppression list handle this? I'm testing and not getting very good results at the moment. Still compiling findings.

![screen shot 2015-06-25 at 11 31 05 am](https://cloud.githubusercontent.com/assets/8238417/8359717/b86dfa0a-1b2d-11e5-88cf-6a031dfa697c.png)

My lists: https://app.suppressionlist.com/#lists/558c298fec8d83625e00000a/edit

**Comment by alexkwolfe** [comment]
This is a bug in SL. Adding two lists with the same name will cause unexpected behavior. Don't do that.

**Comment by alexkwolfe** [comment]
https://github.com/activeprospect/suppressionlist/issues/59
