### ISSUE TITLE
DELETE integration does not work

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-suppressionlist#32]
there are several differences between the setup of ADD and DELETE that might be the culprit, notably I don't see api key being passed at all (maybe it's in a helper?)

**Comment by cgrayson** [comment]
The authorization is done in the helper. If [the KB](https://support.activeprospect.com/hc/en-us/articles/201325609-Adding-and-Removing-List-Items) is to be believed, the request is being made incorrectly. (I.e., there's no mention of a `DELETE https://app.suppressionlist.com/lists/glade_list/items/hot@mail.com` format there.)

**Comment by zalary** [comment]
oh yea, that.  'add' passes the stringified values in the body, but delete adds them to the url like the 'query' which as @cgrayson said, doesn't appear to be valid

**Comment by cgrayson** [comment]
Fixed as of 1.0.2.
