### ISSUE TITLE
Add STEP issues?

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-suppressionlist#34]
Sanity check please:

The following 4 leads came into the account below.
All leads were queried against the SuppressionList and the email was not found.
All leads were successfully added to SL, but this appears to be incorrect.

Lead 4 was received first, which should have resulted in Lead 3 being rejected, as they all have the same email address.

Additionally, when I go to enter in the email address in the SL UI, it says that the email address could not be found. How can this be if the add step was successful?

Can someone look into this please?

1. https://next.leadconduit.com/events/55afd0f7e1399a9957cacddb?event_id=55afd0fae1399a9957cacde7
2. https://next.leadconduit.com/events/55afd0efc30ab4d0624be6bd?event_id=55afd0f2c30ab4d0624be6fd
3. https://next.leadconduit.com/events/55afd0e6166d70c97dc5a97f?event_id=55afd0ea166d70c97dc5a99a
4. https://next.leadconduit.com/events/55afd0dbc30ab4d0624be627?event_id=55afd0e0c30ab4d0624be64e

**Comment by alexkwolfe** [comment]
This was a bug in SuppressionList and it has been resolved.
