### ISSUE TITLE
Question on 404 issue 

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-suppressionlist#35]
I have created a SL for the following flow:

Flow: https://next.leadconduit.com/flows/53c997339d29c9787d00006b/edit
![screen shot 2015-07-23 at 3 02 32 pm](https://cloud.githubusercontent.com/assets/8238417/8860848/2607276a-314c-11e5-829a-16a094373335.png)

SuppressionList: https://app.suppressionlist.com/#lists/55677029f92ea1714400001c/edit

In the event below, it is indicating that there is a 404, even though I've indicated that it is the right SL name. Also, other SL on the same flow/account are working properly. 

Error from event:  Reason -- SuppressionList error (404) Possibly incorrect list_id

https://next.leadconduit.com/events/55b12183cc21494f61e7ca64?event_id=55b12183cc21494f61e7ca66

Can anyone assist?

**Comment by zalary** [comment]
Can't assign myself from the mobile view but I'm looking

**Comment by alexkwolfe** [comment]
The phone number is blank.

**Comment by kcaponeAP** [comment]
ACK. I should have known. Okay. Is there a clearer way we could represent this?

**Comment by alexkwolfe** [comment]
https://github.com/activeprospect/leadconduit-integration-suppressionlist/issues/36

**Comment by kcaponeAP** [comment]
I can dig it. Thanks.
