### ISSUE TITLE
Set URL based on NODE_ENV

### ISSUE THREAD

**Issue by swengmatt** [activeprospect/leadconduit-integration-suppressionlist#38]
This is for the AP developers to be able to use the suppressionlist integration locally without touching the deployed version of suppressionlist, and without having to make weird configurations; just a change in the NODE_ENV to determine which URL to use.

**Comment by swengmatt** [comment]
I have a branch ready to go with this change, but it is dependent on PR #37

**Comment by alexkwolfe** [comment]
Resolved in e1839bae190f115c6a15890756ccec0bd0a894fb.
