### ISSUE TITLE
Values must be URL encoded

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-suppressionlist#56]
I noticed in production today that when querying for an item on a list the values are added to the URL without first URL encoding them. The below value is sent as `Nanagrañny1953@gmail.com` when it should be sent as `Nanagra%C3%B1ny1953%40gmail.com`.

Request:
```
GET https://app.suppressionlist.com/exists/aarp_dedupe/Nanagrañny1953@gmail.com HTTP/1.1
Accept: application/json
Authorization: Basic WDoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKg==
Host: app.suppressionlist.com
Connection: close
```

Response: 
```
HTTP/1.1 400 Bad Request
Server: nginx/1.10.1
Date: Wed, 15 Mar 2017 18:26:11 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 11
Connection: close
Status: 400 Bad Request
Cache-Control: no-cache, no-store, must-revalidate
 invalid URL
```

**Comment by cgrayson** [comment]
Oops. I misunderstood the problem and the fix in #57 – the URL-encoding should _only_ happen on query (i.e., when the value is _in the URL_ 🙄 ). If it happens in the add, then the value is incorrectly double-encoded in SuppressionList.
