### ISSUE TITLE
pre-built field mapping is broken

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-suppressionlist#59]
when using the rc branch, if you select that you want to query a list, choose your list and your field.  you cannot save the flow because the field that it is trying to map to is `list_name` but I believe the validations is looking for `List Names`.

LC tells me the problem, but does not let me edit that mapping and since it is required, I cannot delete it and add it anew.

<img width="1087" alt="screen shot 2017-06-29 at 10 51 03 am" src="https://user-images.githubusercontent.com/338654/27697077-e52c0ce8-5cb8-11e7-988d-6a79b7ff8099.png">

**Comment by cgrayson** [comment]
Fixed & deployed as 1.4.1.
